package com.example.periodictable.dummyData
import com.example.periodictable.model.DialogElements


object ElementSearchDummyData {

    val listAdapter = listOf(
        DialogElements(
            "H",
            "hydrogen",
            " Standard State : Gas",
            "Atomic Mass : 1.0080 u",
            "Electron Configuration : 1s1",
            "  Oxidation States : +1, -1",
            "Electronegativity (Pauling Scale) : 2.2",
            " Atomic Radius (van der Waals) : 120 pm",
            "Ionization Energy : 13.598 eV",
            "Electron Affinity : 0.754 eV",
            "Melting Point : 13.81 K",
            "Boiling Point : 20.28 K",
            "Density : 0.00008988 g/cm³",
            "Year Discovered : 1766"

        ),
        DialogElements(
            "Li",
            "lithium",
            "Standard State : Solid",
            "Atomic Mass : 7.0 u",
            "Electron Configuration : [He]2s1",
            "Oxidation States : +1",
            "Electronegativity (Pauling Scale) : 0.98",
            "Atomic Radius (van der Waals) : 182 pm",
            "Ionization Energy : 5.392 eV",
            "Electron Affinity : 0.618 eV",
            "Melting Point : 453.65 K",
            "Boiling Point : 1615 K",
            "Density : 0.534 g/cm³",
            "Year Discovered : 1817"
        ),
        DialogElements(
            "Na",
            "sodium",
            "Standard State : Solid",
            "Atomic Mass : 22.9897693 u",
            "Electron Configuration : [Ne]3s1",
            "Oxidation States : +1",
            "Electronegativity (Pauling Scale) : 0.93",
            " Atomic Radius (van der Waals) : 227 pm",
            " Ionization Energy : 5.139 eV",
            "Electron Affinity : 0.548 eV",
            "Melting Point : 370.95 K",
            "Boiling Point : 1156 K",
            "Density : 0.97 g/cm³",
            "Year Discovered : 1807"
        ),
        DialogElements(
            "K",
            "potassium",
            "Standard State : Solid",
            " Atomic Mass : 39.0983 u",
            " Electron Configuration : [Ar]4s1",
            "Oxidation States : +1",
            "Electronegativity (Pauling Scale) : 0.82",
            " Atomic Radius (van der Waals) : 275 pm",
            " Ionization Energy : 4.341 eV",
            " Electron Affinity : 0.501 eV",
            "Melting Point : 336.53 K",
            " Boiling Point : 1032 K",
            " Density : 0.89 g/cm³",
            "Year Discovered : 1807"
        ),
        DialogElements(
            "Rb",
            "rubidium",
            "Standard State : Solid",
            "Atomic Mass : 85.468 u",
            "Electron Configuration : [Kr]5s1",
            "Oxidation State : +1",
            "Electronegativity (Pauling Scale) : 0.82",
            " Ionization Energy : 4.177 eV",
            "Ionization Energy : 4.177 eV",
            "Electron Affinity : 0.468 eV",
            "Melting Point : 312.46 K",
            "Boiling Point : 961 K",
            "Density : 1.53 g/cm³",
            "Year Discovered : 1861"
        ),
        DialogElements(
            "Cs",
            "caesium",
            " Standard State : Solid",
            " Atomic Mass : 132.9054520 u",
            "Electron Configuration : [Xe]6s1",
            "Oxidation States : +1",
            "Electronegativity (Pauling Scale) : 0.79",
            "Atomic Radius (van der Waals) : 343 pm",
            "Ionization Energy : 3.894 eV",
            "Electron Affinity : 0.472 eV",
            "Melting Point : 301.59 K",
            "Boiling Point : 944 K",
            "Density : 1.93 g/cm³",
            "Year Discovered : 1860"
        ),
        DialogElements(
            "Fr",
            "francium",
            "Standard State : Solid",
            "Atomic Mass : 223.01973 u",
            "Electron Configuration : [Rn]7s1",
            "Oxidation States : +1",
            "Oxidation States : +1",
            "Atomic Radius (van der Waals) :  348 pm",
            "Ionization Energy : t3.9 eV",
            "Electron Affinity : 0.47 eV",
            "Melting Point : 300 K",
            Year = "Year Discovered : 1939",
            Boiling = "",
            Density = "",

        ),
        DialogElements(
            "Be",
            "beryllium",
            "Standard State : Solid",
            "Atomic Mass : 9.012183 u",
            "Electron Configuration : [He]2s2",
            " Oxidation States : +2",
            "Electronegativity (Pauling Scale) : 1.57",
            "Atomic Radius (van der Waals) : 153 pm",
            "Ionization Energy : 9.323 eV",
            Melting = "Melting Point : 1560 K",
            Boiling =  "  Boiling Point : 2744 K",
            Density =  "Density : 1.85 g/cm³",
            Year = " Year Discovered : 1798",
            electronAffinity = ""

        ),
        DialogElements(
            "Mg",
            "magnesium",
            "Standard State : Solid",
            " Atomic Mass : 24.305 u",
            "Electron Configuration : [Ne]3s2",
            " Oxidation States : +2 ",
            " Electronegativity (Pauling Scale) : 1.31",
            "Atomic Radius (van der Waals) : 173 pm",
            " Ionization Energy : 7.646 eV",
            Melting = "  Melting Point : 923 K",
            Boiling = "Boiling Point : 1363 K",
            Density = "Density	: 1.74 g/cm³",
            Year = "Year Discovered : 1808",
            electronAffinity = ""

        ), DialogElements(
            "Ca",
            "calcium",
            "Standard State : Solid",
            "Atomic Mass : 40.08 u",
            " Electron Configuration : [Ar]4s2",
            "Oxidation States : +2",
            "Electronegativity (Pauling Scale) : 1",
            "Atomic Radius (van der Waals) : 231 pm",
            " Ionization Energy : 6.113 eV",
            Melting ="Melting Point : 1115 K",
            Boiling ="Boiling Point : 1757 K",
            Density ="Density : 1.54 g/cm³",
            Year= "Year Discovered : Ancient",
            electronAffinity=""

        ),
        DialogElements(
            "Sr",
            "strontium",
            "Standard State : Solid",
            "Atomic Mass : 87.62 u",
            "Electron Configuration : [Kr]5s2",
            "Oxidation States : +2",
            "Electronegativity (Pauling Scale) : 0.95",
            "Atomic Radius (van der Waals) : 249 pm",
            "Ionization Energy : 5.695 eV",

            Melting ="Melting Point : 1050 K",
            Boiling ="Boiling Point : 1655 K",
            Density ="Density : 2.64 g/cm³",
            Year= "Year Discovered : 1790",
            electronAffinity=""
        ),
        DialogElements(
            "Ba",
            "barium",
            "Standard State : Solid",
            "Atomic Mass : 137.33 u",
            "Electron Configuration : [Xe]6s2",
            "Oxidation States : +2",
            "Electronegativity (Pauling Scale) : 0.89",
            "Atomic Radius (van der Waals) : 268 pm",
            "Ionization Energy : 5.212 eV",
            Melting ="Melting Point : 1000 K",
            Boiling =" Boiling Point : 2170 K",
            Density ="Density : 3.62 g/cm³",
            Year="Year Discovered : 1808",
            electronAffinity=""
        ),
        DialogElements(
            "Ra",
            "radium",
            "Standard State : Solid",
            "Atomic Mass : 226.02541 u",
            "Electron Configuration : [Rn]7s2",
            "Oxidation States : +2",
            "Electronegativity (Pauling Scale) : 0.9",
            "Atomic Radius (van der Waals) : 283 pm",
            "Ionization Energy : 5.279 eV",
            Melting ="Melting Point : 973 K",
            Boiling ="Boiling Point : 1413 K",
            Density ="Density : 5 g/cm³",
            Year="Year Discovered : 1898",
            electronAffinity=""
        ),
        DialogElements(
            "Sc",
            "scandium",
            "Standard State : Solid",
            "Atomic Mass : 44.95591 u",
            "Electron Configuration : [Ar]4s23d1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.36",
            "Atomic Radius (van der Waals) : 211 pm",
            "Ionization Energy : 6.561 eV",
            "Electron Affinity : 0.188 eV",
            "Melting Point : 1814 K",
            "Boiling Point : 3109 K",
            "Density : 2.99 g/cm³",
            "Year Discovered : 1879"
        ),
        DialogElements(
            "Y",
            "yttrium",
            "Standard State : Solid",
            "Atomic Mass : 88.90584 u",
            "Electron Configuration : [Kr]5s24d1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) :1.22",
            "Atomic Radius (van der Waals) : 219 pm",
            " Ionization Energy : 6.217 eV",
            "Electron Affinity : 0.307 eV",
            "Melting Point : 1795 K",
            "Boiling Point : 3618 K",
            "Density : 4.47 g/cm³",
            "Year Discovered : 1794"

        ),
        DialogElements(
            "La",
            "lanthanum",
            "Standard State : Solid",
            "Atomic Mass : 47.867 u",
            "Electron Configuration : [Ar]4s23d2",
            "Oxidation States : +4, +3, +2",
            "Electronegativity (Pauling Scale) : 1.54",
            "Atomic Radius (van der Waals) : 187 pm",
            "Ionization Energy : 6.828 eV",
            "Electron Affinity : 0.079 eV",
            "Melting Point : 1941 K",
            "Boiling Point : 3560 K",
            "Density : 4.5 g/cm³",
            "Year Discovered : 1791"


        ),
        DialogElements(
            "Ac",
            "actinium",
            "Standard State : Solid",
            "Atomic Mass : 227.02775 u",
            "Electron Configuration : [Rn]7s26d1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.1",
            "Atomic Radius (van der Waals) : 260 pm",
            "Ionization Energy : 5.17 eV",
            Melting = "Melting Point : 1324 K",
            Boiling = "Boiling Point : 3471 K",
            Density = "Density : 10.07 g/cm³",
            Year = "Year Discovered : 1899",
            electronAffinity = ""
        ),
        DialogElements(
            "Ti",
            "titanium",
            "Standard State : Solid",
            "Atomic Mass : 47.867 u",
            "Electron Configuration : [Ar]4s23d2",
            "Oxidation States : +4, +3, +2",
            "Electronegativity (Pauling Scale) : 1.54",
            "Atomic Radius (van der Waals) : 187 pm",
            "Ionization Energy : 6.828 eV",
            Melting ="Melting Point : 1941 K",
            Boiling ="Boiling Point : 3560 K",
            Density = "Density : 4.5 g/cm³",
            Year ="Year Discovered : 1791",
            electronAffinity = ""
        ),
        DialogElements(
            "Zr",
            "zirconium",
            "Standard State : Solid",
            "Atomic Mass : 91.22 u",
            "Electron Configuration : [Kr]5s24d2",
            "Oxidation States : +4",
            "Electronegativity (Pauling Scale) : 1.33",
            "Atomic Radius (van der Waals) : 186 pm",
            "Ionization Energy : 6.634 eV",
            "Electron Affinity : 0.426 eV",
            "Melting Point : 2128 K",
            "Boiling Point : 4682 K",
            "Density : 6.52 g/cm³",
            "Year Discovered : 1789"
        ),
        DialogElements(
            "Hf",
            "hafnium",
            "Standard State : Solid",
            "Atomic Mass : 178.49 u",
            "Electron Configuration : [Xe]6s24f145d2",
            "Oxidation States : +4",
            "Electronegativity (Pauling Scale) : 1.3",
            "Atomic Radius (van der Waals) : 212 pm",
            "Ionization Energy : 6.825 eV",
            Melting = "Melting Point : 2506 K",
            Boiling = "Boiling Point : 4876 K",
            Density = "Density : 13.3 g/cm³",
            Year = "Year Discovered : 1923",
            electronAffinity = ""

        ),
        DialogElements(
            "Rf",
            "rutherfordium",
            "Standard State : Solid",
            "Atomic Mass : 267.122 u",
            "Electron Configuration : [Rn]7s25f146d2",
            "Oxidation States : +4",
            Year = "Year Discovered : 1964",
            electronegativity = "",
            atomicRadius = "",
            ionization = "",
            electronAffinity = "",
            Melting = "",
            Boiling = "",
            Density = ""

        ),
        DialogElements(
            "Ce",
            "cerium",
            "Standard State : Solid",
            "Atomic Mass : 140.116 u",
            "Electron Configuration : [Xe]6s24f15d1",
            "Oxidation States : +4, +3",
            "Electronegativity (Pauling Scale) : 1.12",
            "Atomic Radius (van der Waals) : 235 pm",
            "Ionization Energy : 5.539 eV",
            "Electron Affinity : 0.5 eV",
            "Melting Point : 1071 K",
            "Boiling Point : 3697 K",
            "Density : 6.770 g/cm³",
            "Year Discovered : 1803"
        ),
        DialogElements(
            "Th",
            "thorium",
            "Standard State : Solid",
            "Atomic Mass : 232.038 u",
            " Electron Configuration : [Rn]7s26d2",
            "Oxidation States : +4",
            "Electronegativity (Pauling Scale) : 1.3",
            "Atomic Radius (van der Waals) : 237 pm",
            "Ionization Energy : 6.08 eV",
            Melting = "Melting Point : 2023 K",
            Boiling = "Boiling Point : 5061 K",
            Density = "Density : 11.72 g/cm³",
            Year = "Year Discovered : 1828",
            electronAffinity = ""
        ),
        DialogElements(
            "V",
            "vanadium",
            "Standard State : Solid",
            "Atomic Mass : 50.9415 u",
            "Electron Configuration : [Ar]4s23d3",
            "Oxidation States : +5, +4, +3, +2",
            "Electronegativity (Pauling Scale) : 1.63",
            "Atomic Radius (van der Waals) : 179 pm",
            "Ionization Energy : 6.746 eV",
            "Electron Affinity : 0.525 eV",
            "Melting Point : 2183 K",
            "Boiling Point : 3680 K",
            "Density : 6.0 g/cm³",
            "Year Discovered : 1801"
        ),
        DialogElements(
            "Nb",
            "niobium",
            "Standard State : Solid",
            "Atomic Mass : 92.90637 u",
            "Electron Configuration : [Kr]5s14d4",
            "Oxidation States : +5, +3",
            "Electronegativity (Pauling Scale) : 1.6",
            "Atomic Radius (van der Waals) : 207 pm",
            "Ionization Energy : 6.759 eV",
            "Electron Affinity : 0.893 eV",
            "Melting Point : 2750 K",
            "Boiling Point : 5017 K",
            "Density : 8.57 g/cm³",
            "Year Discovered : 1801"
        ),
        DialogElements(
            "Ta",
            "tantalum",
            "Standard State : Solid",
            "Atomic Mass : 180.9479 u",
            "Electron Configuration :[Xe]6s24f145d3",
            "Oxidation States : +5",
            "Electronegativity (Pauling Scale) : 1.5",
            "Atomic Radius (van der Waals) : 217 pm",
            "Ionization Energy : 7.89 eV",
            "Electron Affinity : 0.322 eV",
            "Melting Point : 3290 K",
            "Boiling Point : 5731 K",
            "Density : 16.4 g/cm³",
            "Year Discovered : 1802"
        ),
        DialogElements(
            "Db",
            "dubnium",
            " Standard State : Solid",
            " Atomic Mass : 268.126 u",
            "Electron Configuration : [Rn]7s25f146d3",
            "Oxidation States : 5, 4, 3",
            Year = "Year Discovered : 1967",
            electronegativity = "",
            atomicRadius = "",
            ionization = "",
            electronAffinity = "",
            Melting = "",
            Boiling = "",
            Density = ""


        ),
        DialogElements(
            "pr",
            "praseodymium",
            "Standard State : Solid",
            "Atomic Mass : 140.90766 u",
            "Electron Configuration : [Xe]6s24f3",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.13",
            "Atomic Radius (van der Waals) : 239 pm",
            "Ionization Energy : 5.464 eV",
            Melting = "Melting Point : 1204 K",
            Boiling = "Boiling Point : 3793 K",
            Density = "Density : 6.77 g/cm³",
            Year = "Year Discovered : 1885",
            electronAffinity = ""
        ),
        DialogElements(
            "Pa",
            "protactinium",
            "Standard State : Solid",
            "Atomic Mass : 231.03588 u",
            "Electron Configuration : [Rn]7s25f26d1",
            "Oxidation States : +5, +4",
            "Electronegativity (Pauling Scale) : 1.5",
            "Atomic Radius (van der Waals) : 243 pm",
            "Ionization Energy : 5.89 eV",
            Melting = "Melting Point : 1845 K",
            Density = "Density : 15.37 g/cm³",
            Year = " Year Discovered : 1913",
            Boiling = "",
            electronAffinity = ""

        ),
        DialogElements(
            "Cr",
            "chromium",
            "Standard State : Solid",
            "Atomic Mass : 51.996 u",
            "Electron Configuration : [Ar]3d54s1",
            "Oxidation States : +6, +3, +2",
            "Electronegativity (Pauling Scale) : 1.66",
            "Atomic Radius (van der Waals) : 189 pm",
            "Ionization Energy : 6.767 eV",
            "Electron Affinity : 0.666 eV",
            "Melting Point : 2180 K",
            "Boiling Point : 2944 K",
            "Density : 7.15 g/cm³",
            "Year Discovered : 1797"
        ),
        DialogElements(
            "Mo",
            "molybdenum",
            "Standard State : Solid",
            "Atomic Mass : 95.95 u",
            "Electron Configuration : [Kr]5s14d5",
            "Oxidation States : +6",
            "Electronegativity (Pauling Scale) : 2.16",
            "Atomic Radius (van der Waals) : 209 pm",
            "Ionization Energy : 7.092 eV",
            "Electron Affinity : 0.746 eV",
            "Melting Point : 2896 K",
            "Boiling Point : 4912 K",
            "Density : 10.2 g/cm³",
            "Year Discovered : 1778"
        ),
        DialogElements(
            "W",
            "tungsten",
            "Standard State : Solid",
            "Atomic Mass : 183.84 u",
            "Electron Configuration : [Xe]6s24f145d4",
            "Oxidation States : +6",
            "Electronegativity (Pauling Scale) : 2.36",
            "Atomic Radius (van der Waals) : 210 pm",
            "Ionization Energy : 7.98 eV",
            "Electron Affinity : 0.815 eV",
            "Melting Point : 3695 K",
            "Boiling Point : 5828 K",
            "Density : 19.3 g/cm³",
            "Year Discovered : 1783"
        ),
        DialogElements(
            "Sg",
            "seaborgium",
            "Standard State : Solid",
            "Atomic Mass : 269.128 u",
            "Electron Configuration : [Rn]7s25f146d4",
            "Oxidation States : 6, 5, 4, 3, 0",
            Year = "Year Discovered : 1974",
            electronegativity = "",
            atomicRadius = "",
            ionization = "",
            electronAffinity = "",
            Melting = "",
            Boiling = "",
            Density = ""

        ),
        DialogElements(
            "Nd",
            "neodymium",
            "Standard State : Solid",
            "Atomic Mass : 144.24 u",
            "Electron Configuration : [Xe]6s24f4",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.14",
            "Atomic Radius (van der Waals) : 229 pm",
            "Ionization Energy : 5.525 eV",
            Melting = "Melting Point : 1294 K",
            Boiling = "Boiling Point : 3347 K",
            Density = "Density : 7.01 g/cm³",
            Year = "Year Discovered : 1885",
            electronAffinity = ""
        ),
        DialogElements(
            "U",
            "uranium",
            "Standard State : Solid",
            "Atomic Mass : 238.0289 u",
            " Electron Configuration : [Rn]7s25f36d1",
            "Oxidation States : +6, +5, +4, +3",
            "Oxidation States : +6, +5, +4, +3",
            "Atomic Radius (van der Waals) : 240 pm",
            "Ionization Energy : 6.194 eV",
            Melting = " Melting Point : 1408 K",
            Boiling = "Boiling Point : 4404 K",
            Density = "Density : 18.95 g/cm³",
            Year = "Year Discovered : 1789",
            electronAffinity = ""
        ),
        DialogElements(
            "Mn",
            "manganese",
            "Standard State : Solid",
            "Atomic Mass : 54.93804 u",
            "Electron Configuration : [Ar]4s23d5",
            "Oxidation States : +7, +4, +3, +2",
            "Electronegativity (Pauling Scale) : 1.55",
            " Atomic Radius (van der Waals) : 197 pm",
            "Ionization Energy : 7.434 eV",
            Melting = "Melting Point : 1519 K",
            Boiling = "Boiling Point : 2334 K",
            Density = "Density : 7.3 g/cm³",
            Year = "Year Discovered : 1774",
            electronAffinity = ""

        ),
        DialogElements(
            "Tc",
            "technetium",
            "Standard State : Solid",
            "Atomic Mass : 96.90636 u",
            "Electron Configuration : [Kr]5s24d5",
            "Oxidation States : +7, +6, +4",
            "Electronegativity (Pauling Scale) : 1.9",
            "Atomic Radius (van der Waals) : 209 pm",
            "Ionization Energy : 7.28 eV",
            Melting = "Melting Point : 2430 K",
            Boiling = "Boiling Point : 4538 K",
            Density = " Density : 11 g/cm³",
            Year = " Year Discovered : 1937",
            electronAffinity = ""
        ),
        DialogElements(
            "Re",
            "rhenium",
            "Standard State : Solid",
            "Atomic Mass : 186.207 u",
            "Electron Configuration : [Xe]6s24f145d5",
            "Oxidation States : +7, +6, +4",
            "Electronegativity (Pauling Scale) : 1.9",
            "Atomic Radius (van der Waals) : 217 pm",
            "Ionization Energy : 7.88 eV",
            Melting = "Melting Point : 3459 K",
            Boiling = "Boiling Point : 5869 K",
            Density =  "Density : 20.8 g/cm³",
            Year = " Year Discovered : 1925 ",
            electronAffinity = ""
        ),
        DialogElements(
            "Bh",
            "bohrium",
            "Standard State : Solid",
            "Atomic Mass : 270.133 u",
            "Electron Configuration : [Rn]7s25f146d5",
            "Oxidation States : 7, 5, 4, 3",
            Year = "Year Discovered : 1976",
            electronegativity = "",
            atomicRadius = "",
            ionization = "",
            electronAffinity = "",
            Melting = "",
            Boiling = "",
            Density = ""

        ),
        DialogElements(
            "Pm",
            "promethium",
            "Standard State : Solid",
            "Atomic Mass : 144.91276 u",
            "Electron Configuration : [Xe]6s24f5",
            "Oxidation States : +3",
            atomicRadius = "Atomic Radius (van der Waals) : 236 pm",
            ionization = "Ionization Energy : 5.55 eV",
            Melting = "Melting Point : 1315 K",
            Boiling = "Boiling Point : 3273 K",
            Density = "Density : 7.26 g/cm³",
            Year = "Year Discovered : 1945",
            electronegativity = "",
            electronAffinity = ""
        ),
        DialogElements(
            "Np",
            "neptunium",
            "Standard State : Solid",
            "Atomic Mass : 237.048172 u",
            " Electron Configuration : [Rn]7s25f46d1",
            "Oxidation States : +6, +5, +4, +3",
            "Electronegativity (Pauling Scale) : 1.36",
            "Atomic Radius (van der Waals) : 221 pm",
            "Ionization Energy : 6.266 eV",
            Melting = "Melting Point : 917 K",
            Boiling = "Boiling Point : 4175 K",
            Density = "Density : 20.25 g/cm³",
            Year =  "Year Discovered : 1940",
            electronAffinity = ""
        ),
        DialogElements(
            "Fe",
            "iron",
            "Standard State : Solid",
            " Atomic Mass : 55.84 u",
            "Electron Configuration : [Ar]4s23d6",
            "Oxidation States : +3, +2",
            "Electronegativity (Pauling Scale) : 1.83",
            "Atomic Radius (van der Waals) : 194 pm",
            "Ionization Energy : 7.902 eV",
            "Electron Affinity : 0.163 eV",
            "Melting Point : 1811 K",
            "Boiling Point : 3134 K",
            "Density : 7.874 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Ru",
            "ruthenium",
            "Standard State : Solid",
            "Atomic Mass : 101.1 u",
            "Electron Configuration : [Kr]5s14d7",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 2.2",
            "Atomic Radius (van der Waals) : 207 pm",
            "Ionization Energy : 7.361 eV",
            " Electron Affinity : 1.05 eV",
            "Melting Point : 2607 K",
            "Boiling Point : 4423 K",
            "Density : 12.1 g/cm³",
            "Year Discovered : 1827"
        ),
        DialogElements(
            "Os",
            "osmium",
            "Standard State : Solid",
            "Atomic Mass : 190.2 u",
            "Electron Configuration : [Xe]6s24f145d6",
            "Oxidation States : +4, +3",
            "Electronegativity (Pauling Scale) : 2.2",
            "Atomic Radius (van der Waals) : 216 pm",
            "Ionization Energy : 8.7 eV",
            "Electron Affinity : 1.1 eV",
            "Melting Point : 3306 K",
            "Boiling Point : 5285 K",
            "Density : 22.57 g/cm³",
            "Year Discovered : 1803"
        ),
        DialogElements(
            "Hs",
            "hassium",
            "Standard State : Solid",
            "Atomic Mass : 269.1336 u",
            "Electron Configuration : [Rn]7s25f146d6",
            " Oxidation States : 8, 6, 5, 4, 3, 2",
            Year = " Year Discovered : 1984",
            electronegativity = "", atomicRadius = "",ionization =  "",electronAffinity =  "", Melting = "",Boiling =  "", Density = ""


        ),
        DialogElements(
            "Sm",
            "samarium",
            "Standard State : Solid",
            "Atomic Mass : 150.4 u",
            "Electron Configuration : [Xe]6s24f6",
            "Oxidation States : +3, +2",
            "Electronegativity (Pauling Scale) : 1.17",
            "Atomic Radius (van der Waals) : 229 pm",
            "Ionization Energy : 5.644 eV",
            Melting = " Melting Point : 1347 K",
            Boiling = " Boiling Point : 2067 K",
            Density = "Density : 7.52 g/cm³",
            Year = "Year Discovered : 1879",
            electronAffinity = ""
        ),
        DialogElements(
            "Pu",
            "plutonium",
            "Standard State : Solid",
            "Atomic Mass : 244.06420 u",
            "Electron Configuration : [Rn]7s25f6",
            "Oxidation States : +6, +5, +4, +3",
            "Electronegativity (Pauling Scale) : 1.28",
            "Atomic Radius (van der Waals) : 243 pm",
            "Ionization Energy : 6.06 eV",
            Melting = "Melting Point : 913 K",
            Boiling = "Boiling Point : 3501 K",
            Density = "Density : 19.84 g/cm³",
            Year = "Year Discovered : 1940",
            electronAffinity = ""
        ),
        DialogElements(
            "Co",
            "cobalt",
            "Standard State : Solid",
            "Atomic Mass : 58.93319 u",
            "Electron Configuration : [Ar]4s23d7",
            "Oxidation States : +3, +2",
            "Electronegativity (Pauling Scale) : 1.88",
            "Atomic Radius (van der Waals) : 192 pm",
            "Ionization Energy : 7.881 eV",
            "Electron Affinity : 0.661 eV",
            "Melting Point : 1768 K",
            "Boiling Point : 3200 K",
            "Density : 8.86 g/cm³",
            "Year Discovered : 1735"
        ),
        DialogElements(
            "Rh",
            "rhodium",
            "Standard State : Solid",
            " Atomic Mass : 102.9055 u",
            " Electron Configuration : [Kr]5s14d8",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 2.28",
            "Atomic Radius (van der Waals) : 195 pm",
            "Ionization Energy : 7.459 eV",
            "Electron Affinity : 1.137 eV",
            "Melting Point : 2237 K",
            "Boiling Point : 3968 K",
            "Density : 12.4 g/cm³",
            "Year Discovered : 1803"
        ),
        DialogElements(
            "Ir",
            "iridium",
            "Standard State : Solid",
            "Atomic Mass : 192.22 u",
            "Electron Configuration : [Xe]6s24f145d7",
            "Oxidation States : +4, +3",
            "Electronegativity (Pauling Scale) : 2.2",
            "Atomic Radius (van der Waals) : 202 pm",
            "Ionization Energy : 9.1 eV",
            "  Electron Affinity : 1.565 eV",
            "Melting Point : 2719 K",
            "Boiling Point : 4701 K",
            "Density : 22.42 g/cm³",
            "Year Discovered : 1803"
        ),
        DialogElements(
            "Mt",
            "meitnerium",
            "Standard State : Solid",
            "Atomic Mass : 277.154 u",
            " Electron Configuration : [Rn]7s25f146d7",
            "Oxidation States : 9, 8, 6, 4, 3, 1",
            Year = "Year Discovered : 1982",
            electronegativity = "", atomicRadius = "",ionization =  "",electronAffinity =  "", Melting = "",Boiling =  "", Density = ""
        ),
        DialogElements(
            "Eu",
            "europium",
            "Standard State :Solid",
            "Atomic Mass : 151.964 u",
            "Electron Configuration : [Xe]6s24f7",
            "Oxidation States : +3, +2",
            "",
            "Atomic Radius (van der Waals) : 233 pm",
            "Ionization Energy : 5.670 eV",
            "",
            "Melting Point : 1095 K",
            "Boiling Point : 1802 K",
            "Density : 5.24 g/cm³",
            "Year Discovered : 1901"
        ),
        DialogElements(
            "Am",
            "americium",
            "Standard State : Solid",
            "Atomic Mass : 243.061380 u",
            "Electron Configuration : [Rn]7s25f7",
            "Oxidation States : +6, +5, +4, +3",
            " Electronegativity (Pauling Scale) : 1.3",
            "Atomic Radius (van der Waals) : 244 pm",
            "Ionization Energy : 5.993 eV",
            "",
            "Melting Point : 1449 K",
            "Boiling Point : 2284 K",
            "Density : 13.69 g/cm³",
            "Year Discovered : 1944"
        ),
        DialogElements(
            "Ni",
            "nickel",
            "Standard State :Solid",
            "Atomic Mass : 58.693 u",
            "Electron Configuration : [Ar]4s23d8",
            "Oxidation States : +3, +2",
            "Electronegativity (Pauling Scale) : 1.91",
            " Atomic Radius (van der Waals) : 163 pm",
            "Ionization Energy : 7.640 eV",
            " Electron Affinity : 1.156 eV",
            " Melting Point : 1728 K",
            "Boiling Point : 3186 K",
            "Density : 8.912 g/cm³",
            "Year Discovered : 1751"
        ),
        DialogElements(
            "Pd",
            "palladium",
            " Standard State : Solid",
            "Atomic Mass : 106.42 u",
            "Electron Configuration : [Kr]4d10",
            "Oxidation States : +3, +2",
            "Electronegativity (Pauling Scale) : 2.2",
            "Atomic Radius (van der Waals) : 202 pm",
            "Ionization Energy : 8.337 eV",
            " Electron Affinity : 0.557 eV",
            "Melting Point : 1828.05 K",
            "Boiling Point : 3236 K",
            "Density : 12.0 g/cm³",
            "Year Discovered : 1803"
        ),
        DialogElements(
            "Pt",
            "platinum",
            "Standard State : Solid",
            "Atomic Mass : 195.08 u",
            "Electron Configuration : [Xe]6s14f145d9",
            " Oxidation States : +4, +2",
            " Electronegativity (Pauling Scale) : 2.28",
            "Atomic Radius (van der Waals) : 209 pm",
            "Ionization Energy : 9 eV",
            "Electron Affinity : 2.128 eV",
            "Melting Point : 2041.55 K",
            "Boiling Point : 4098 K",
            "Density : 21.46 g/cm³",
            "Year Discovered : 1735"
        ),
        DialogElements(
            "Ds",
            "darmstadtium",
            "Standard State : Solid (Expected)",
            "Atomic Mass : 282.166 u",
            "Electron Configuration : [Rn]7s25f146d8",
            "Oxidation States : 8, 6, 4, 2, 0",
            "", "", "", "", "", "", "",
            " Year Discovered : 1994"
        ),
        DialogElements(
            "Gd",
            "gadolinium",
            "Standard State : Solid",
            "Atomic Mass : 157.2 u",
            "Electron Configuration : [Xe]6s24f75d1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.2",
            "Atomic Radius (van der Waals) : 237 pm",
            "Ionization Energy : 6.150 eV",
            "",
            "Melting Point : 1586 K",
            "Boiling Point : 3546 K",
            "Density : 7.90 g/cm³",
            "Year Discovered : 1880"
        ),
        DialogElements(
            "cm",
            "curium",
            "Standard State : Solid",
            "Atomic Mass : 247.07035 u",
            "Electron Configuration : [Rn]7s25f76d1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.3",
            "Atomic Radius (van der Waals) : 245 pm",
            "Ionization Energy : 6.02 eV",
            "",
            "Melting Point : 1618 K",
            "Boiling Point : 3400 K",
            " Density : 13.51 g/cm³",
            "Year Discovered : 1944"
        ),
        DialogElements(
            "Cu",
            "copper",
            "Standard State : Solid",
            "Atomic Mass : 63.55 u",
            "Electron Configuration : [Ar]4s13d10",
            "Oxidation States : +2, +1",
            "Electronegativity (Pauling Scale) : 1.9",
            "Atomic Radius (van der Waals) : 140 pm",
            " Ionization Energy : 7.726 eV",
            "Electron Affinity : 1.228 eV",
            "Melting Point : 1357.77 K",
            "Boiling Point : 2835 K",
            "Density : 8.933 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Au",
            "gold",
            "Standard State : Solid",
            "Atomic Mass : 196.96657 u",
            "Electron Configuration : [Xe]6s14f145d10",
            "Oxidation States : +3, +1",
            "Electronegativity (Pauling Scale) : 2.54",
            "Ionization Energy : 9.226 eV",
            " Ionization Energy : 9.226 eV",
            "Electron Affinity : 2.309 eV",
            "Melting Point : 1337.33 K",
            "Boiling Point : 3129 K",
            "Density : 19.282 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Rg",
            "roentgenium",
            "Standard State : Solid (Expected)",
            " Atomic Mass : 282.169 u",
            " Electron Configuration : [Rn]7s25f146d9",
            " Oxidation States : 5, 3, 1, -1",
            "", "", "", "", "", "", "",
            " Year Discovered : 1994"
        ),
        DialogElements(
            "Tb",
            "terbium",
            " Standard State : Solid",
            "Atomic Mass : 158.92535 u",
            "Electron Configuration : [Xe]6s24f9",
            " Oxidation States : +3",
            "",
            "Atomic Radius (van der Waals) : 221 pm",
            "Ionization Energy : 5.864 eV",
            "",
            "Melting Point : 1629 K",
            "Boiling Point : 3503 K",
            "Density : 8.23 g/cm³",
            "Year Discovered : 1843"
        ),
        DialogElements(
            "Bk",
            "berkelium",
            "Standard State : Solid",
            "Atomic Mass : 247.07031 u",
            "Electron Configuration : [Rn]7s25f9",
            "Oxidation States : +4, +3",
            "Electronegativity (Pauling Scale) : 1.3",
            "Atomic Radius (van der Waals) : 244 pm",
            "Ionization Energy : 6.23 eV",
            "",
            "Melting Point : 1323 K",
            "",
            "Density : 14 g/cm³",
            "Year Discovered : 1949"
        ),
        DialogElements(
            "Zn",
            "zinc",
            "Standard State : Solid",
            "Atomic Mass : 65.4 u",
            "Electron Configuration : [Ar]4s23d10",
            "Oxidation States : +2",
            "Electronegativity (Pauling Scale) : 1.65",
            "Atomic Radius (van der Waals) : 139 pm",
            "Ionization Energy : 9.394 eV",
            "",
            "Melting Point : 692.68 K",
            "Boiling Point : 1180 K",
            "Density : 7.134 g/cm³",
            " Year Discovered : 1746"
        ),
        DialogElements(
            "Cd",
            "cadmium",
            "Standard State : Solid",
            "Atomic Mass : 112.41 u",
            "Electron Configuration : [Kr]5s24d10",
            "Oxidation States : +2",
            "Electronegativity (Pauling Scale) : 1.69",
            "Atomic Radius (van der Waals) : 158 pm",
            "Ionization Energy : 8.994 eV",
            "",
            "Melting Point : 594.22 K",
            "Boiling Point : 1040 K",
            "Density : 8.69 g/cm³",
            "Year Discovered : 1817"
        ),
        DialogElements(
            "Hg",
            "mercury",
            "Standard State : Liquid",
            "Atomic Mass : 200.59 u",
            "Electron Configuration : [Xe]6s24f145d10",
            "Oxidation States : +2, +1",
            "Electronegativity (Pauling Scale) : 2",
            "Atomic Radius (van der Waals) : 209 pm",
            "Ionization Energy : 10.438 eV",
            "",
            "Melting Point : 234.32 K",
            "Boiling Point : 629.88 K",
            "Density : 13.5336 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Cn",
            "copernicium",
            "Standard State : Solid (Expected)",
            "Atomic Mass : 286.179 u",
            "Electron Configuration : [Rn]7s25f146d10",
            " Oxidation States : 2, 1, 0",
            "", "", "", "", "", "", "",
            "Year Discovered : 1996"
        ),
        DialogElements(
            "Dy",
            "dysprosium",
            " Standard State : Solid",
            "Atomic Mass : 162.500 u",
            "Electron Configuration : [Xe]6s24f10",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.22",
            "Atomic Radius (van der Waals) : 229 pm",
            "Ionization Energy : 5.939 eV",
            "",
            "Melting Point : 1685 K",
            "Boiling Point : 2840 K",
            "Density : 8.55 g/cm³",
            "Year Discovered : 1886"
        ),
        DialogElements(
            "Cf",
            "californium",
            "Standard State : Solid",
            "Atomic Mass : 251.07959 u",
            "Electron Configuration : [Rn]7s25f10",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.3",
            "Atomic Radius (van der Waals) : 245 pm",
            "Ionization Energy : 6.30 eV",
            "",
            "Melting Point : 1173 K", "", "",
            " Year Discovered : 1950"
        ),
        DialogElements(
            "B",
            "boron",
            "Standard State : Solid",
            "Atomic Mass : 10.81 u",
            "Electron Configuration : [He]2s22p1",
            "Oxidation States : +3",
            " Electronegativity (Pauling Scale) :2.04",
            "Atomic Radius (van der Waals) : 192 pm",
            "Ionization Energy : 8.298 eV",
            "Electron Affinity : 0.277 eV",
            "Melting Point : 2348 K",
            "Boiling Point : 4273 K",
            "Density : 2.37 g/cm³",
            "Year Discovered : 1808"
        ),
        DialogElements(
            "Al",
            "aluminum",
            " Standard State : Solid",
            "Atomic Mass : 26.981538 u",
            "Electron Configuration : [Ne]3s23p1",
            " Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.61",
            "Atomic Radius (van der Waals) : 184 pm",
            "Ionization Energy : 5.986 eV",
            " Electron Affinity : 0.441 eV",
            " Melting Point : 933.437 K",
            "Boiling Point : 2792 K",
            "Density : 2.70 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Ga",
            "gallium",
            "Standard State : Solid",
            "Atomic Mass : 69.723 u",
            "Electron Configuration : [Ar]4s23d104p1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.81",
            "Atomic Radius (van der Waals) : 187 pm",
            "Ionization Energy : 5.999 eV",
            "Electron Affinity : 0.3 eV",
            " Melting Point : 302.91 K",
            "Boiling Point : 2477 K",
            "Density : 5.91 g/cm³",
            " Year Discovered : 1875"
        ),
        DialogElements(
            "In",
            "indium",
            "Standard State : Solid",
            " Atomic Mass : 114.818 u",
            "Electron Configuration : [Kr]5s24d105p1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.78",
            "Atomic Radius (van der Waals) : 193 pm",
            "Ionization Energy : 5.786 eV",
            "Electron Affinity : 0.3 eV",
            "Melting Point : 429.75 K",
            "Boiling Point : 2345 K",
            "Density : 7.31 g/cm³",
            "Year Discovered : 1863"
        ),
        DialogElements(
            "Tl",
            "thallium",
            "Standard State : Solid",
            "Atomic Mass : 204.383 u",
            "Electron Configuration :[Xe]6s24f145d106p1",
            " Oxidation States : +3, +1",
            "Electronegativity (Pauling Scale) : 1.62",
            " Atomic Radius (van der Waals) : 196 pm",
            "Ionization Energy : 6.108 eV",
            "Electron Affinity : 0.2 eV",
            "Melting Point : 577 K",
            "Boiling Point : 1746 K",
            "Density : 11.8 g/cm³",
            "Year Discovered : 1861"
        ),
        DialogElements(
            "Nh",
            "nihonium",
            "Standard State : Solid (Expected)",
            "Atomic Mass : 286.182 u",
            "Electron Configuration : [Rn]5f146d107s27p1",
            "", "", "", "", "", "", "", "",
            "Year Discovered : 2004"
        ),
        DialogElements(
            "Ho",
            "holmium",
            "Standard State : Solid",
            "Atomic Mass : 164.93033 u",
            "Electron Configuration : [Xe]6s24f11",
            "Oxidation States : +3",
            " Electronegativity (Pauling Scale) :1.23",
            "Atomic Radius (van der Waals) : 216 pm",
            "Ionization Energy : 6.022 eV",
            "",
            "Melting Point : 1747 K",
            "Boiling Point : 2973 K",
            "Density : 8.80 g/cm³",
            "Year Discovered : 1878"
        ),
        DialogElements(
            "Es",
            "einsteinium",
            "Standard State : Solid",
            " Atomic Mass : 252.0830 u",
            " Electron Configuration : [Rn]7s25f11",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.3",
            "Atomic Radius (van der Waals) : 245 pm",
            "Ionization Energy : 6.42 eV",
            "",
            "Melting Point : 1133 K",
            "", "",
            " Year Discovered : 1952"
        ),
        DialogElements(
            "C",
            "carbon",
            "Standard State : Solid",
            "Atomic Mass : 12.011 u",
            "Electron Configuration : [He]2s22p2",
            "Oxidation States : +4, +2, -4",
            "Electronegativity (Pauling Scale) : 2.55",
            "Atomic Radius (van der Waals) : 170 pm",
            "Ionization Energy : 11.260 eV",
            "Electron Affinity : 1.263 eV",
            "Melting Point : 3823 K",
            "Boiling Point : 4098 K",
            "Density : 2.2670 g/cm³",
            "Year Discovered :Ancient"
        ),
        DialogElements(
            "Si",
            "silicon",
            "Standard State: Solid",
            "Atomic Mass : 28.085 u",
            "Electron Configuration : [Ne]3s23p2",
            " Oxidation States : +4, +2, -4",
            "Electronegativity (Pauling Scale) : 1.9",
            "Atomic Radius (van der Waals) : 210 pm",
            "Ionization Energy : 8.152 eV",
            " Electron Affinity : 1.385 eV",
            "Melting Point : 1687 K",
            "Boiling Point : 3538 K",
            "Density : 2.3296 g/cm³",
            "Year Discovered : 1854"
        ),
        DialogElements(
            "Ge",
            "germanium",
            "Standard State : Solid",
            "Atomic Mass : 72.63 u",
            " Electron Configuration : [Ar]4s23d104p2",
            "Oxidation States : +4, +2",
            "Electronegativity (Pauling Scale) : 2.01",
            "Atomic Radius (van der Waals) : 211 pm",
            "Ionization Energy : 7.900 eV",
            "Electron Affinity : 1.35 eV",
            "Melting Point : 1211.4 K",
            "Boiling Point : 3106 K",
            "Density : 5.323 g/cm³",
            "Year Discovered : 1886"
        ),
        DialogElements(
            "Sn",
            "tin",
            "Standard State : Solid",
            "Atomic Mass : 118.71 u",
            "Electron Configuration : [Kr]5s24d105p2",
            "Oxidation States : +4, +2",
            " Electronegativity (Pauling Scale) : 1.96",
            "Atomic Radius (van der Waals) : 217 pm",
            "Ionization Energy : 7.344 eV",
            "Electron Affinity : 1.2 eV",
            "Melting Point : 505.08 K",
            "Boiling Point : 2875 K",
            "Density : 7.287 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Pb",
            "lead",
            " Standard State : Solid",
            "Atomic Mass : 207 u",
            " Electron Configuration : [Xe]6s24f145d106p2",
            "Oxidation States : +4, +2",
            "Electronegativity (Pauling Scale) : 2.33",
            "Atomic Radius (van der Waals) : 202 pm",
            "Ionization Energy : 7.417 eV",
            " Electron Affinity : 0.36 eV",
            "Melting Point : 600.61 K",
            "Boiling Point : 2022 K",
            "Density : 11.342 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Fl",
            "flerovium",
            " Standard State : Solid (Expected)",
            "Atomic Mass : 290.192 u",
            "Electron Configuration : [Rn]7s27p25f146d10",
            "Oxidation States : 6, 4,2, 1, 0",
            "", "", "", "", "", "", "",
            "Year Discovered : 1998"
        ),
        DialogElements(
            "Er",
            "erbium",
            "Standard State : Solid",
            "Atomic Mass : 167.26 u",
            "Electron Configuration : [Xe]6s24f12",
            "Oxidation States : +3",
            " Electronegativity (Pauling Scale) : 1.24",
            "Atomic Radius (van der Waals) : 235 pm",
            "Ionization Energy : 6.108 eV",
            "",
            "Melting Point : 1802 K",
            " Boiling Point : 3141 K",
            "Density : 9.07 g/cm³",
            "Year Discovered : 1843"
        ),
        DialogElements(
            "Fm",
            "fermium",
            "Standard State : Solid",
            "Atomic Mass : 257.09511 u",
            " Electron Configuration : [Rn]5f127s2",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.3",
            "",
            "Ionization Energy : 6.50 eV",
            "",
            "Melting Point : 1800 K", "", "",
            "Year Discovere : 1952"
        ),
        DialogElements(
            "N",
            "nitrogen",
            "Standard State : Gas",
            " Atomic Mass : 14.007 u",
            " Electron Configuration :[He]2s22p3",
            "Oxidation States : +5, +4, +3, +2, +1, -1, -2, -3",
            "Electronegativity (Pauling Scale) : 3.04",
            " Atomic Radius (van der Waals) : 155 pm",
            "Ionization Energy : 14.534 eV",
            "",
            "Melting Point : 63.15 K",
            "Boiling Point : 77.36 K",
            "Density : 0.0012506 g/cm³",
            "Year Discovered : 1772"
        ),
        DialogElements(
            "P",
            "phosphorus",
            "Standard State : Solid",
            "Atomic Mass : 30.97376200 u",
            "Electron Configuration : [Ne]3s23p3",
            "Oxidation States : +5, +3, -3",
            " Electronegativity (Pauling Scale) : 2.19",
            " Atomic Radius (van der Waals) : 180 pm",
            "Ionization Energy : 10.487 eV",
            "Electron Affinity : 0.746 eV",
            "Melting Point : 317.3 K",
            "Boiling Point : 553.65 K",
            "Density : 1.82 g/cm³",
            "Year Discovered : 1669"
        ),
        DialogElements(
            "As",
            "arsenic",
            "Standard State : Solid",
            "Atomic Mass : 74.92159 u",
            "Electron Configuration : [Ar]4s23d104p3",
            "Oxidation States : +5, +3, -3",
            "Electronegativity (Pauling Scale) : 2.18",
            "Atomic Radius (van der Waals) : 185 pm",
            "Electron Affinity : 0.81 eV",
            " Electron Affinity : 0.81 eV",
            "Melting Point : 1090 K",
            "Boiling Point : 887 K",
            "Density : 5.776 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Sb",
            "antimony",
            " Standard State : Solid",
            "Atomic Mass : 121.760 u",
            "Electron Configuration : [Kr]5s24d105p3",
            "Oxidation States : +5, +3, -3",
            " Electronegativity (Pauling Scale) : 2.05",
            "Atomic Radius (van der Waals) : 206 pm",
            "Ionization Energy : 8.64 eV",
            "Electron Affinity : 1.07 eV",
            "Melting Point : 903.78 K",
            "Boiling Point : 1860 K",
            "Density : 6.685 g/cm³",
            "Year Discovered : Ancient"
        ),
        DialogElements(
            "Bi",
            "bismuth",
            "Standard State : Solid",
            "Atomic Mass : 208.98040 u",
            "Electron Configuration : [Xe]6s24f145d106p3",
            "Oxidation States : +5, +3",
            "Electronegativity (Pauling Scale) : 2.02",
            "Atomic Radius (van der Waals) : 207 pm",
            "Ionization Energy : 7.289 eV",
            "Electron Affinity : 0.946 eV",
            " Melting Point : 544.55 K",
            "Boiling Point : 1837 K",
            "Density : 9.807 g/cm³",
            "Year Discovered : 1753"
        ),
        DialogElements(
            "Mc",
            "moscovium",
            "Standard State : Solid (Expected)",
            " Atomic Mass : 290.196 u",
            " Electron Configuration : [Rn]7s27p35f146d10",
            "Oxidation States : 3, 1",
            "", "", "", "", "", "", "",
            "Year Discovered : 2003"
        ),
        DialogElements(
            "Tm",
            "thulium",
            " Standard State : Solid",
            "Atomic Mass : 168.93422 u",
            "Electron Configuration : [Xe]6s24f13",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.25",
            "Atomic Radius (van der Waals) : 227 pm",
            "Ionization Energy : 6.184 eV",
            "",
            "Melting Point : 1818 K",
            "Boiling Point : 2223 K",
            "Density : 9.32 g/cm³",
            "Year Discovered : 1879"
        ),
        DialogElements(
            "Md",
            "mendelevium",
            "Standard State : Solid",
            " Atomic Mass : 258.09843 u",
            " Electron Configuration : [Rn]7s25f13",
            "Oxidation States : +3, +2",
            "Electronegativity (Pauling Scale) : 1.3",
            "",
            "Ionization Energy : 6.58 eV",
            "",
            "Melting Point : 1100 K",
            "", "",
            " Year Discovered : 1955"
        ),
        DialogElements(
            "O",
            "oxygen",
            "Standard State : Gas",
            "Atomic Mass : 15.999 u",
            "Electron Configuration : [He]2s22p4",
            "Oxidation States : -2",
            "Electronegativity (Pauling Scale) : 3.44",
            "Atomic Radius (van der Waals) : 152 pm",
            " Ionization Energy : 13.618 eV",
            " Electron Affinity : 1.461 eV",
            "Melting Point : 54.36 K",
            "Boiling Point : 90.2 K",
            "Density : 0.001429 g/cm³",
            "Year Discovered : 1774"
        ),
        DialogElements(
            "S",
            "sulfur",
            "Standard State : Solid",
            "Atomic Mass : 32.07 u",
            "Electron Configuration : [Ne]3s23p4",
            " Oxidation States : +6, +4, -2",
            "Electronegativity (Pauling Scale) : 2.58",
            "Atomic Radius (van der Waals) : 180 pm",
            "Ionization Energy : 10.360 eV",
            "Electron Affinity : 2.077 eV",
            "Melting Point : 388.36 K",
            "Boiling Point : 717.75 K",
            "Density : 2.067 g/cm³",
            "Year Discovered : Ancient"
        ), DialogElements(
            "Se",
            "selenium",
            " Standard State : Solid",
            "Atomic Mass : 78.97 u",
            "Electron Configuration : [Ar]4s23d104p4",
            "Oxidation States : +6, +4, -2",
            "Electronegativity (Pauling Scale) : 2.55",
            "Atomic Radius (van der Waals) : 190 pm",
            "Ionization Energy : 9.752 eV",
            "Electron Affinity : 2.021 eV",
            "Melting Point : 493.65 K",
            "Boiling Point : 958 K",
            "Density : 4.809 g/cm³",
            "Year Discovered : 1817"
        ),
        DialogElements(
            "Te",
            "tellurium",
            "Standard State : Solid",
            "Atomic Mass : 127.6 u",
            "Electron Configuration : [Kr]5s24d105p4",
            "Oxidation States : +6, +4, -2",
            "Electronegativity (Pauling Scale) : 2.1",
            "Atomic Radius (van der Waals) : 206 pm",
            "Ionization Energy : 9.010 eV",
            "Electron Affinity : 1.971 eV",
            "Melting Point : 722.66 K",
            "Boiling Point : 1261 K",
            "Density : 6.232 g/cm³",
            " Year Discovered : 1782"
        ),
        DialogElements(
            "Po",
            "polonium",
            "Standard State : Solid",
            "Atomic Mass : 208.98243 u",
            "Electron Configuration : [Xe]6s24f145d106p4",
            "Oxidation States : +4, +2",
            "Electronegativity (Pauling Scale) : 2",
            "Atomic Radius (van der Waals) : 197 pm",
            "Ionization Energy : 8.417 eV",
            "Electron Affinity : 1.9 eV",
            "Melting Point : 527 K",
            "Boiling Point : 1235 K",
            "Density : 9.32 g/cm³",
            "Year Discovered : 1898"
        ),
        DialogElements(
            "Lv",
            "livermorium",
            "Standard State : Solid (Expected)",
            "Atomic Mass : 293.205 u",
            "Electron Configuration : [Rn]7s27p45f146d10",
            "Oxidation States : +4, +2, -2",
            "", "", "", "", "", "", "",
            "Year Discovered : 2000"
        ),
        DialogElements(
            "Yb",
            "ytterbium",
            "Standard State : Solid",
            "Atomic Mass : 173.05 u",
            "Electron Configuration : [Xe]6s24f14",
            "Oxidation States : +3, +2",
            "",
            "Atomic Radius (van der Waals) : 242 pm",
            "Ionization Energy : 6.254 eV",
            "",
            "Melting Point : 1092 K",
            "Boiling Point : 1469 K",
            "Density : 6.90 g/cm³",
            "Year Discovered : 1878"
        ),
        DialogElements(
            "No",
            "nobelium",
            "Standard State : Solid",
            "Atomic Mass : 259.10100 u",
            "Electron Configuration : [Rn]7s25f14",
            "Oxidation States : +3, +2",
            "Electronegativity (Pauling Scale) : 1.3",
            "",
            "Ionization Energy : 6.65 eV",
            "",
            "Melting Point : 1100 K",
            "", "", "Year Discovered : 1957"

        ),
        DialogElements(
            "F",
            "fluorine",
            "Standard State : Gas",
            "Atomic Mass : 18.99840316 u",
            "Electron Configuration : [He]2s22p5",
            "Oxidation States : -1",
            "Electronegativity (Pauling Scale) : 3.98",
            "Atomic Radius (van der Waals) : 135 pm",
            "Ionization Energy : 17.423 eV",
            " Electron Affinity : 3.339 eV",
            "Melting Point : 53.53 K",
            "Boiling Point : 85.03 K",
            " Density : 0.001696 g/cm³",
            "Year Discovered : 1670"
        ),
        DialogElements(
            "Cl",
            "chlorine",
            "Standard State : Gas",
            "Atomic Mass : 35.45 u",
            "Electron Configuration : [Ne]3s23p5",
            "Oxidation States : +7, +5, +1, -1",
            " Electronegativity (Pauling Scale) : 3.16",
            " Atomic Radius (van der Waals) : 175 pm",
            "Ionization Energy : 12.968 eV",
            "Electron Affinity : 3.617 eV",
            "Melting Point : 171.65 K",
            "Boiling Point : 239.11 K",
            "Density : 0.003214 g/cm³",
            "Year Discovered : 1774"
        ),
        DialogElements(
            "Br",
            "bromine",
            "Standard State : Liquid",
            "Atomic Mass : 79.90 u",
            "Electron Configuration : [Ar]4s23d104p5",
            "Oxidation States : +5, +1, -1",
            "Electronegativity (Pauling Scale) : 2.96",
            "Atomic Radius (van der Waals) : 183 pm",
            "Ionization Energy : 11.814 eV",
            "Electron Affinity : 3.365 eV",
            "Melting Point : 265.95 K",
            "Boiling Point : 331.95 K",
            "Density : 3.11 g/cm³",
            "Year Discovered : 1826"
        ),
        DialogElements(
            "I",
            "iodine",
            "Standard State : Solid",
            "Atomic Mass : 126.9045 u",
            "Electron Configuration : [Kr]5s24d105p5",
            "Oxidation States : +7, +5, +1, -1",
            "Electronegativity (Pauling Scale) : 2.66",
            "Atomic Radius (van der Waals) : 198 pm",
            "Ionization Energy : 10.451 eV",
            "Electron Affinity : 3.059 eV",
            "Melting Point :386.85 K",
            "Boiling Point : 457.55 K",
            "Density : 4.93 g/cm³",
            "Year Discovered : 1811"
        ),
        DialogElements(
            "At",
            "astatine",
            "Standard State : Solid",
            "Atomic Mass : 209.98715 u",
            "Electron Configuration : [Xe]6s24f145d106p5",
            "Oxidation States : 7, 5, 3, 1, -1",
            "Electronegativity (Pauling Scale) : 2.2",
            "Atomic Radius (van der Waals) : 202 pm",
            "Ionization Energy : 9.5 eV",
            "Electron Affinity : 2.8 eV",
            "Melting Point : 575 K",
            "",
            "Density : 7 g/cm³",
            " Year Discovered : 1940"
        ),
        DialogElements(
            "Ts",
            "tennessine",
            "Standard State : Solid (Expected)",
            "Atomic Mass : 294.211 u",
            "Electron Configuration : [Rn]7s27p55f146d10",
            "Oxidation States : +5, +3, +1, -1",
            "", "", "", "", "", "", "",
            "Year Discovered : 2010"
        ),
        DialogElements(
            "Lu",
            "lutetium",
            "Standard State : Solid",
            " Atomic Mass : 174.9668 u",
            "Electron Configuration : [Xe]6s24f145d1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.27",
            "Atomic Radius (van der Waals) : 221 pm",
            "Ionization Energy : 5.426 eV",
            "",
            "Melting Point : 1936 K",
            "Boiling Point : 3675 K",
            "Density : 9.84 g/cm³",
            "Year Discovered : 1907"
        ),
        DialogElements(
            "Lr",
            "lawrencium",
            "Standard State : Solid",
            "Atomic Mass : 266.120 u",
            "Electron Configuration : [Rn]7s25f146d1",
            "Oxidation States : +3",
            "Electronegativity (Pauling Scale) : 1.3",
            "", "",
            "Electronegativity (Pauling Scale) : 1.3",
            " Melting Point : 1900 K", "", "",
            "Year Discovered : 1961"
        ),
        DialogElements(
            "HE",
            "helium",
            "Standard State : Gas",
            "Atomic Mass : 4.00260 u",
            "Electron Configuration : 1s2",
            "Oxidation States : 0",
            "",
            "Atomic Radius (van der Waals) : 140 pm",
            "Ionization Energy : 24.587 eV",
            "",
            "Melting Point : 0.95 K",
            " Boiling Point : 4.22 K",
            "Density : 0.0001785 g/cm³",
            "Year Discovered : 1868"
        ),
        DialogElements(
            "Ne",
            "neon",
            "Standard State : Gas",
            "Atomic Mass : 20.180 u",
            "Electron Configuration : [He]2s22p6",
            "Oxidation States : 0",
            "",
            "Oxidation States : 0",
            "Ionization Energy : 21.565 eV",
            "",
            "Melting Point : 24.56 K",
            "Boiling Point : 27.07 K",
            "Density : 0.0008999 g/cm³",
            "Year Discovered : 1898"
        ),
        DialogElements(
            "Ar",
            "argon",
            "Standard State : Gas",
            " Atomic Mass : 39.9 u",
            "Electron Configuration : [Ne]3s23p6",
            "Oxidation States : 0",
            "",
            "Atomic Radius (van der Waals) : 188 pm",
            "Ionization Energy : 15.760 eV",
            "",
            "Melting Point : 83.8 K",
            "Boiling Point : 87.3 K",
            "Density : 0.0017837 g/cm³",
            "Year Discovered : 1894"
        ),
        DialogElements(
            "Kr",
            "krypton",
            "Standard State : Gas",
            "Atomic Mass : 83.80 u",
            "Electron Configuration : [Ar]4s23d104p6",
            "Oxidation States : 0",
            "Electronegativity (Pauling Scale) : 3",
            " Atomic Radius (van der Waals) : 202 pm",
            "Ionization Energy : 14.000 eV",
            "",
            "Melting Point : 115.79 K",
            "Boiling Point : 119.93 K",
            " Density : 0.003733 g/cm³",
            "Year Discovered : 1898"
        ),
        DialogElements(
            "Xe",
            "xenon",
            "Standard State : Gas",
            "Atomic Mass : 131.29 u",
            "Electron Configuration : [Kr]5s24d105p6",
            "Oxidation States : 0",
            "Electronegativity (Pauling Scale) : 2.6",
            "Atomic Radius (van der Waals) : 216 pm",
            "Ionization Energy : 12.130 eV",
            "",
            "Melting Point : 161.36 K",
            "Boiling Point : 165.03 K",
            "Density : 0.005887 g/cm³",
            "Year Discovered : 1898"
        ),
        DialogElements(
            "Rn",
            "radon",
            "Standard State : Gas",
            "Atomic Mass : 222.01758 u",
            "Electron Configuration : [Xe]6s24f145d106p6",
            "Oxidation States : 0",
            "",
            "Atomic Radius (van der Waals) : 220 pm",
            "Ionization Energy : 10.745 eV",
            "",
            "Melting Point : 202 K",
            "Boiling Point : 211.45 K",
            "Density : 0.00973 g/cm³",
            "Year Discovered : 1900"
        ),

        DialogElements(
            "Og",
            "oganesson",
            "Standard State : Gas (Expected)",
            "Atomic Mass : 295.216 u",
            "Electron Configuration : [Rn]7s27p65f146d10",
            "Oxidation States : +6, +4, +2, +1, 0, -1",
            "", "", "", "", "", "", "",
            "Year Discovered : 2006"
        ),
        DialogElements(
            "Ag",
            "silver",
            "Standard State : Solid",
            "Atomic Mass : 107.868 u",
            "Electron Configuration : [Kr]5s14d10",
            "Oxidation States : +1",
            "Electronegativity (Pauling Scale) : 1.93",
            "Atomic Radius (van der Waals) : 172 pm",
            "Ionization Energy : 7.576 eV",
            "Electron Affinity : 1.302 eV",
            "Melting Point : 1234.93 K",
            "Boiling Point : 2435 K",
            "Density : 10.501 g/cm³",
            "Year Discovered : Ancient"
        )
    )
}